
services:
  knowledge-app:
    build: .
    ports:
      - "${APP_PORT:-8501}:${APP_PORT:-8501}"
    env_file:
      - .env
    environment:
      - SELENIUM_REMOTE_URL=http://selenium:4444/wd/hub
    volumes:
      - /mnt/d/transcriptions:/app/transcriptions:rw
    user: "1000:1000"  # Ensure container runs with proper user ID
    restart: unless-stopped
    container_name: knowledge-app
    depends_on:
      - selenium
    networks:
      - knowledge-net

  selenium:
    image: selenium/standalone-chrome:latest
    ports:
      - "4444:4444"
    environment:
      - SE_NODE_MAX_SESSIONS=2
    volumes:
      - /dev/shm:/dev/shm
    restart: unless-stopped
    container_name: knowledge-selenium
    networks:
      - knowledge-net

networks:
  knowledge-net:
    driver: bridge