
services:
  knowledge-app:
    build: .
    ports:
      - "8501:8501"
    environment:
      - APP_PORT=8501
      - APP_HOST=0.0.0.0
      - DOWNLOAD_FOLDER=/app/transcriptions
      - TRANSCRIPTION_FOLDER=/app/transcriptions
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
    volumes:
      - /mnt/s/transcriptions:/app/transcriptions
    restart: unless-stopped
    container_name: knowledge-app